Recruit/Recruit.MVC/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Recruit.MVC.Models;
using Newtonsoft.Json;

// /controladores empresa.
namespace Recruit.MVC.Controllers
{
    public class EmpresaController : Controller
    {
        string apiURL = "http://http://localhost:53907/";

        public async Task<IActionResult> Index()
        {
            List<EmpresaModel> EmpresaList = new List<EmpresaModel>();

            using (var Empresa = new HttpClient())
            {

                Empresa.BaseAddress = new Uri(apiURL);
                Empresa.DefaultRequestHeaders.Accept.Clear();
                Empresa.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("apllication/jason"));

                HttpResponseMessage res = await Empresa.GetAsync("api/Empresa");
                if (res.IsSuccessStatusCode)
                {
                    var Empresaresult = res.Content.ReadAsStringAsync().Result;
                    EmpresaList = JsonConvert.DeserializeObject<List<EmpresaModel>>(Empresaresult);
                }

                return View(EmpresaList);
            }
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
    }
}

Recruit/Recruit.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recruit.MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    
<div id="art-main">
    <header class="art-header">
     
        <h1 class="art-headline" data-left="6.85%">
            <a href="#">ReclutaSoft</a>
        </h1>
        <h2 class="art-slogan" data-left="11.11%">Software de Reclutamiento</h2>

        <nav class="art-nav">
            <ul class="art-hmenu">
                <li><a href="home.html" class="active">ReclutaSoft</a></li>
                <li><a href="@Url.Action("Index", "TRecCandidato")">Candidatos</a></li>
                <li><a href="@Url.Action("Index", "Idioma")">Idioma</a></li>
                <li><a href="@Url.Action("Index", "Estado")">Estado</a></li>
                <li><a href="@Url.Action("Index", "Entrevista")">Entrevista</a></li>
                <li><a href="@Url.Action("Index", "Probabilidad")">Probabilidad</a></li>
                <li><a href="@Url.Action("Index", "Reclutador")">Reclutador</a></li>
                <li><a href="@Url.Action("Index", "OfertaTrabajo")">Oferta Trabajo</a></li>
                <li><a href="@Url.Action("Index", "OfertaReclutador")">Oferta Reclutador</a></li>
                <li><a href="@Url.Action("Index", "Bitacora")">Bitacora</a></li>
                <li><a href="@Url.Action("Index", "Usuarios")">Usuarios</a></li>
                <li><a href="@Url.Action("Index", "Configuracion")">Configuracion</a></li>
                <li><a href="@Url.Action("Index", "Empresa")">Empresa</a></li>

            </ul>

        </nav>
    </header>
    <div class="art-sheet clearfix">
        <div class="art-layout-wrapper">
            <div class="art-content-layout">
                <div class="art-content-layout-row">
                    <div class="art-layout-cell art-content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="art-footer">
        <div class="art-footer-inner">
            <div class="art-content-layout-wrapper layout-item-0">
                <div class="art-content-layout layout-item-1">
                    <div class="art-content-layout-row">
                        <div class="art-layout-cell layout-item-2" style="width: 50%">
                            <p>Copyright © 2011-2012. All Rights Reserved.</p>
                        </div><div class="art-layout-cell layout-item-2" style="width: 50%">
                            <p style="text-align: right;"><a href="#">Privacy Policy</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#">Terms Of Use</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#">About</a></p>
                        </div>
                    </div>
                </div>
            </div>

            <p class="art-page-footer">
                <span id="art-footnote-links"><a href="http://www.nzso.com/" target="_blank">Web Template</a> created by nzso.</span>
            </p>
        </div>
    </footer>

</div>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>